<?php require_once __DIR__ . '/ajax.file_upload.js.phtml' ?>

<?php $view->scriptalicious()->addSrc('jQuery', '/js/jquery-ui-1.10.4.custom.min.js') ?>
<?php $view->scriptalicious()->addSrc('imagesloaded', '/js/imagesloaded.pkgd.min.js')
    ->addDependency('imagesloaded', 'jQuery') ?>
<?php $view->scriptalicious()->addSrc('image_picker', '/js/image-picker.min.js')
    ->addDependency('image_picker', 'jQuery') ?>
<?php $view->scriptalicious()->addSrc('masonry', '/js/masonry.pkgd.min.js')
    ->addDependency('masonry', 'jQuery') ?>
<?php $view->scriptalicious()->addSrc('gbili_popup', '/js/gbili/popup.js') ?>

<?php ob_start() ?>
<script type="text/javascript">
/* Filename: <?= __FILE__ ?> */
/*
 * When used alongside image_picker, gbiliuploader is presented as a popup
 */
gbili = gbili || {};
gbili.upm = gbili.upm || {};
//Attach valid response event listeners
(function () {
    var gbiliUploaderInitImagePicker = function() {
        $("select.image-picker").imagepicker();
        var $container = $("select.image-picker.masonry").next('ul.thumbnails');
        $container.imagesLoaded(function () {
            $container.masonry({
                itemSelector: 'li',
            })
        });
    };

    var gbiliUploaderReloadImagePicker = function() {
        var currentImagePicker = $("ul.thumbnails");
        currentImagePicker.remove();
        gbiliUploaderInitImagePicker();
    };

    /*
     * Reload Image picker with new image
     *
     * 1.Append the uploaded image to the image select
     * 2.Reload image-picker on select so that the new image
     * is available for select
     */
    gbiliUploaderAddImageToSelectForm = function(response) {
        var options = '';
        var callbackReturn = response.callbackReturn;
        var lastItemKey = callbackReturn.length-1;
        for( key in  callbackReturn) {
            if (lastItemKey == key) {
                options = options + '<option data-img-src="' + callbackReturn[key].mediaSrc + '" value="' + callbackReturn[key].mediaId + '" selected="selected">';
            } else {
                options = options + '<option data-img-src="' + callbackReturn[key].mediaSrc + '" value="' + callbackReturn[key].mediaId + '" >';
            }
        }
        var selectElement = $('select.image-picker');
        selectElement.html(selectElement.html() + options);
    };

    var handleResponseWithImage = function(event) {
        gbiliUploaderAddImageToSelectForm(event.params.response);
        gbiliUploaderReloadImagePicker();
        event.isPropagationStopped = true;
    };

    // Add listeners for responses with images
    var statusesWithImageInResponse = ['success', 'partial'];
    for (var i in statusesWithImageInResponse) {
        gbili.event.addListener('#<?= $formId ?>.submit.success.response.valid.' + statusesWithImageInResponse[i], handleResponseWithImage, 100);
    }
    // Add event listener after popup has been changed
    gbili.event.addListener('#<?= $formId ?>.submit.after', function (event) {
        gbili.popup.initButtonHide();
    }, 2);

    /*
     * Add a button to the below the image picker selector, 
     * that will trigger the popup form
     */
    var createShowPopupButton = function() {
        var buttonShowPopup = '<div class="gbiliuploader-show-popup-button"><a class="btn btn-primary">+</a></div>';
        var cunt = $('.gbili-add-media-button-container');
        var butt = '<div class="gbiliuploader-show-popup-button"><a class="btn btn-primary">+</a></div>';
        cunt.append(butt);
    }();

    gbili.popup.init({
        containerCssSelector: '#<?= $this->popupDivId ?>',
        buttonHideCssSelector: '#<?= $this->popupDivId ?> > a.gbiliuploader-hide-popup-button',
        buttonShowCssSelector: 'div.gbiliuploader-show-popup-button a.btn',
    });
 
    //Important to load the image picker after the add media button
    gbiliUploaderInitImagePicker();
})();

</script>
<?php $add_button_to_image_picker = ob_get_clean()?>

<?php $view->scriptalicious()->addInline('gbiliuploader_image_picker_aware_media_upload', $add_button_to_image_picker)
    ->addDependency('gbiliuploader_image_picker_aware_media_upload', 'masonry')
    ->addDependency('gbiliuploader_image_picker_aware_media_upload', 'image_picker')
    ->addDependency('gbiliuploader_image_picker_aware_media_upload', 'imagesloaded')
    ->addDependency('gbiliuploader_image_picker_aware_media_upload', 'gbiliuploader_ajax_file_upload')
    ->addDependency('gbiliuploader_image_picker_aware_media_upload', 'gbili_popup')?>

<?php unset($add_button_to_image_picker) ?>
